/**
 * 앱에서 사용하는 Lucide 아이콘 이름 (단일 세트, 이모지 금지 — CLAUDE.md §6).
 * components/ui/icon.tsx 의 매핑이 이 union 을 모두 충족(satisfies)한다.
 */
export type IconName =
  // 카테고리 (category.ts)
  | "utensils"
  | "coffee"
  | "gift"
  | "shopping-bag"
  | "landmark"
  | "bed"
  | "bus"
  | "circle-dot"
  // 역할 (roles.ts)
  | "crown"
  | "pencil"
  | "eye"
  | "eye-off"
  // 코어
  | "plus"
  | "minus"
  | "search"
  | "share"
  | "check"
  | "route"
  | "map-pin"
  | "calendar"
  | "wallet"
  | "users"
  | "bell"
  | "settings"
  | "sliders"
  | "shield"
  | "message"
  | "upload"
  | "x"
  | "chevron-right"
  | "chevron-left"
  | "chevron-down"
  | "chevron-up"
  | "chevrons-right"
  | "chevrons-left"
  | "arrow-right"
  | "arrow-left"
  | "mail"
  | "lock"
  | "user"
  | "link"
  | "copy"
  | "file-plus"
  | "folder-plus"
  | "bookmark"
  | "layers"
  // 여행 커버 아이콘
  | "building"
  | "palmtree"
  | "mountain"
  | "globe"
  | "waves"
  // 기타
  | "trending-up"
  | "piggy-bank"
  | "sparkles"
  | "home"
  | "refresh"
  | "activity"
  | "wrench"
  | "help"
  | "clock"
  | "grip-vertical"
  | "alert"
  | "info"
  | "trash"
  | "more-horizontal"
  | "log-out"
  | "plane"
  | "arrow-up-down"
  // 팜플렛(2차)
  | "image"
  | "luggage"
  | "compass"
  | "list-checks"
  | "file-text"
  | "qr-code"
  | "download"
  | "inbox";
