import {
  Utensils,
  Coffee,
  Gift,
  ShoppingBag,
  Landmark,
  Bed,
  Bus,
  CircleDot,
  Crown,
  Pencil,
  Eye,
  EyeOff,
  Plus,
  Minus,
  Search,
  Share2,
  Check,
  Route,
  MapPin,
  Calendar,
  Wallet,
  Users,
  Bell,
  Settings,
  SlidersHorizontal,
  Shield,
  MessageSquare,
  Upload,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ChevronsRight,
  ChevronsLeft,
  ArrowRight,
  ArrowLeft,
  Mail,
  Lock,
  User,
  Link2,
  Copy,
  FilePlus2,
  FolderPlus,
  Bookmark,
  Layers,
  Building2,
  TreePalm,
  Mountain,
  Globe,
  Waves,
  TrendingUp,
  PiggyBank,
  Sparkles,
  House,
  RefreshCw,
  Activity,
  Wrench,
  CircleHelp,
  Clock,
  GripVertical,
  CircleAlert,
  Info,
  Trash2,
  MoreHorizontal,
  Menu,
  List,
  LogOut,
  Plane,
  ArrowUpDown,
  Image as ImageIcon,
  Luggage,
  Compass,
  ListChecks,
  FileText,
  QrCode,
  Download,
  Inbox,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

import type { IconName } from "@/lib/constants/icons";

/**
 * 단일 아이콘 세트 (Lucide). 이모지 금지 (CLAUDE.md §6).
 * kebab-case 이름(데이터·상수와 동일) → Lucide 컴포넌트 매핑.
 * `satisfies Record<IconName, …>` 로 모든 IconName 이 매핑됐는지 컴파일 타임 보장.
 */
const ICONS = {
  utensils: Utensils,
  coffee: Coffee,
  gift: Gift,
  "shopping-bag": ShoppingBag,
  landmark: Landmark,
  bed: Bed,
  bus: Bus,
  "circle-dot": CircleDot,
  crown: Crown,
  pencil: Pencil,
  eye: Eye,
  "eye-off": EyeOff,
  plus: Plus,
  minus: Minus,
  search: Search,
  share: Share2,
  check: Check,
  route: Route,
  "map-pin": MapPin,
  calendar: Calendar,
  wallet: Wallet,
  users: Users,
  bell: Bell,
  settings: Settings,
  sliders: SlidersHorizontal,
  shield: Shield,
  message: MessageSquare,
  upload: Upload,
  x: X,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevrons-right": ChevronsRight,
  "chevrons-left": ChevronsLeft,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  mail: Mail,
  lock: Lock,
  user: User,
  link: Link2,
  copy: Copy,
  "file-plus": FilePlus2,
  "folder-plus": FolderPlus,
  bookmark: Bookmark,
  layers: Layers,
  building: Building2,
  palmtree: TreePalm,
  mountain: Mountain,
  globe: Globe,
  waves: Waves,
  "trending-up": TrendingUp,
  "piggy-bank": PiggyBank,
  sparkles: Sparkles,
  home: House,
  refresh: RefreshCw,
  activity: Activity,
  wrench: Wrench,
  help: CircleHelp,
  clock: Clock,
  "grip-vertical": GripVertical,
  alert: CircleAlert,
  info: Info,
  trash: Trash2,
  "more-horizontal": MoreHorizontal,
  menu: Menu,
  list: List,
  "log-out": LogOut,
  plane: Plane,
  "arrow-up-down": ArrowUpDown,
  image: ImageIcon,
  luggage: Luggage,
  compass: Compass,
  "list-checks": ListChecks,
  "file-text": FileText,
  "qr-code": QrCode,
  download: Download,
  inbox: Inbox,
} satisfies Record<IconName, LucideIcon>;

export interface IconProps extends Omit<LucideProps, "ref"> {
  name: IconName;
}

export function Icon({ name, size = 18, strokeWidth = 2, ...props }: IconProps) {
  const Cmp = ICONS[name];
  return <Cmp size={size} strokeWidth={strokeWidth} aria-hidden {...props} />;
}

export type { IconName };
